#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

python3.10 -m venv venv
source venv/bin/activate

python -m pip install -r requirements/requirements-dev.txt

echo "Bootstrap completed!"
echo "To launch the server, run:"
echo "tools/quart run"
